# Generated by Django 4.2.27 on 2026-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('part', 'Part'), ('accessories', 'Accessories')], max_length=20),
        ),
    ]
