# Generated by Django 4.2.30 on 2026-04-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Open Box', 'Open Box'), ('Used', 'Used')], default='Brand New', max_length=20),
        ),
    ]
