# Generated by Django 4.2.30 on 2026-09-28 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client Name', max_length=150)),
                ('role_or_title', models.CharField(blank=True, help_text='e.g. Software Engineer, TechLab', max_length=150)),
                ('quote', models.TextField(help_text='Client testimonial quote')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 Stars (★★★★★)'), (4, '4 Stars (★★★★☆)'), (3, '3 Stars (★★★☆☆)'), (2, '2 Stars (★★☆☆☆)'), (1, '1 Star (★☆☆☆☆)')], default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('service_rendered', models.CharField(blank=True, help_text='e.g. MacBook Logic Board Repair, OEM Screen', max_length=150)),
                ('is_approved', models.BooleanField(default=True, help_text='Approve to display on website')),
                ('is_featured', models.BooleanField(default=True, help_text='Feature on homepage carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
