# Generated by Django 4.2.27 on 2026-04-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Subtle title for the media briefing.', max_length=255)),
                ('video_url', models.URLField(help_text='Link to YouTube, Vimeo, or social media video.')),
                ('thumbnail', models.ImageField(help_text='Premium thumbnail image for the gallery.', upload_to='videos/thumbnails/')),
                ('is_featured', models.BooleanField(default=True, help_text='Should this appear in the homepage carousel?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
