# Generated by Django 4.2.27 on 2026-04-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Optional. If left blank, we'll try to fetch the YouTube placeholder.", null=True, upload_to='videos/thumbnails/'),
        ),
    ]
