# Generated by Django 4.2.27 on 2026-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0004_alter_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='unknown@compupartz.com', max_length=254),
            preserve_default=False,
        ),
    ]
