# Generated by Django 4.2.30 on 2026-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0007_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations_display',
            field=models.TextField(blank=True, null=True),
        ),
    ]
